server:
  port: 8765

spring:
  application:
    name: service-feign

# D版本之后的feign默认没有开启 断路器
feign.hystrix.enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/