server:
  port: 8762

spring:
  application:
    # \u8FD9\u4E2A\u5F88\u91CD\u8981\uFF0C\u5404\u4E2A\u670D\u52A1\u4E4B\u95F4\u8C03\u7528\u90FD\u662F\u6839\u636E\u8FD9\u4E2A name
    name: eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


