server:
  port: 8888

spring:
  application:
    name: config-server
  # config配置
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/iszhangsc/SpringcloudConfig
          # 配置仓库路径
          search-paths: respo
          # 公开仓库不需要填写账号密码
          username:
          password:
      # 仓库的分支
      label: master

