server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          # \u914D\u7F6Egit\u4ED3\u5E93\u5730\u5740
          uri: https://github.com/iszhangsc/SpringcloudConfig
          # \u914D\u7F6E\u4ED3\u5E93\u8DEF\u5F84
          search-paths: respo
          # \u516C\u5F00\u4ED3\u5E93\u4E0D\u9700\u8981\u586B\u5199\u8D26\u53F7\u5BC6\u7801
          username:
          password:
      # \u4ED3\u5E93\u7684\u5206\u652F
      label: master

